[package]
name = "inv-server"
version = "0.1.0"
edition = "2021"

[dependencies]
inv-common = { path = "../common" }

bincode = "1.3.3"
lazy_static = "1.4.0"
serde = "1.0"
serde_derive = "1.0"
fastrand = "2.1"
